[Support] Fix -Wpessimizing-move in Mustache.cpp (NFC)
/llvm-project/llvm/lib/Support/Mustache.cpp:299:27:
error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
    PrevToken.TokenBody = std::move(Unindented.str());
                          ^
/llvm-project/llvm/lib/Support/Mustache.cpp:299:27: note: remove std::move call here
    PrevToken.TokenBody = std::move(Unindented.str());
                          ^~~~~~~~~~                ~
1 error generated.